export enum ComponentEvent {

    INIT = 'INIT',

    IDLE = 'IDLE',


    DESTROY = 'DESTROY',

    CREATE_REQUEST      = 'CREATE:REQUEST',
    CREATE_WAIT_INPUT   = 'CREATE:WAIT_INPUT',
    CREATE_INPUT        = 'CREATE:INPUT',
    CREATE_PENDING      = 'CREATE:PENDING',
    CREATE_DONE         = 'CREATE:DONE',

    RETRIEVE_REQUEST    = 'RETRIEVE:REQUEST',
    RETRIEVE_PENDING    = 'RETRIEVE:PENDING',
    RETRIEVE_DONE       = 'RETRIEVE:DONE',

    UPDATE_REQUEST      = 'UPDATE:REQUEST',
    UPDATE_WAIT_INPUT   = 'UPDATE:WAIT_INPUT',
    UPDATE_INPUT        = 'UPDATE:INPUT',
    UPDATE_PENDING      = 'UPDATE:PENDING',
    UPDATE_DONE         = 'UPDATE:DONE',

    DELETE_REQUEST      = 'DELETE:REQUEST',
    DELETE_PENDING      = 'DELETE:PPENDING',
    DELETE_DONE         = 'DELETE:DONE'
};